version: '2'
services:
  zookeeper:
    image: debezium/zookeeper:1.1
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka:1.1
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  mysql:
    image: debezium/example-mysql:1.1
    ports:
     - 3305:3305
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw 
     - MYSQL_DB=inventory
  pgsql:
    image: crunchydata/crunchy-postgres:centos7-12.2-4.3.0
    environment:
     - PGHOST=/tmp
     - PG_MODE=primary
     - PG_PRIMARY_PORT=5432
     - PG_PRIMARY_USER=postgres
     - PG_DATABASE=testdb
     - PG_PRIMARY_PASSWORD=debezium
     - PG_PASSWORD=not
     - PG_ROOT_PASSWORD=matter
     - PG_USER=debezium
    volumes:
     - ./pg-primary-vol:/pgdata
    ports:
    - "5432"
  connect:
    image: debezium-jdbc:latest
    build:
      context: debezium-jdbc
    ports:
     - 8083:8083
     - 5005:5005
    links:
     - kafka
     - zookeeper
     - mysql
     - pgsql
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses
